### ISSUE TITLE
Malformed document id gets reported to error reporter

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#515] opened 2017-12-08 19:48 UTC
Malformed document error (i.e. when using the doc endpoint and providing a malformed document id) gets reported as an internal server error while the helpful error is reported to the error reporter.

**Comment by erikgrinaker** [comment] 2017-12-08 19:52
This is fixed on `master`, dupe of #334. We'll deploy this along with the new metadata handling on Tuesday.

**Closed by erikgrinaker** 2017-12-08 19:52 UTC
Labels: bug/minor
