### ISSUE TITLE
Array slices broken when used on attributes

### ISSUE THREAD

**Issue by erikgrinaker** [sanity-io/gradient#587] opened 2018-01-26 15:42 UTC
Consider this document:

```json
{
  "_id": "id",
  "_type": "test",
  "v_array": [1, "string", true, null, [1, 2, 3], {"key": "value"}]
}
```

Using a `..` range subscript on the array yields:

```
gradient> *[_id=="id"][0].v_array[0..2]
[
  1,
  "string",
  true,
  null,
  [
    1,
    2,
    3
  ],
  {
    "key": "value"
  }
]
```

It should only return the first three elements. The same goes for `...` subscripts.

**Comment by atombender** [comment] 2018-01-26 16:18
Looks like dupe of #445 (related to the query plan graph). Works fine on a literal.

**Closed by atombender** 2018-01-26 16:18 UTC
Labels: bug/minor
