### ISSUE TITLE
Deep joins on a single line not working properly

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#382] opened 2017-05-03 04:20 UTC
`url2` appears, but `url1` never materializes

```
*[_type == 'movie'][0..1]{"chars": castMembers[0..1]{
  "url1":person->image.asset->url,
  person->{
    "url2":image.asset->url
  }
}}
```

**Comment by erikgrinaker** [comment] 2017-11-28 14:20
Dupe of #415

**Closed by erikgrinaker** 2017-11-28 14:20 UTC
Labels: bug/major
