### ISSUE TITLE
More helpful error message when paginating beyond `index.max_result_window` (10k)

### ISSUE THREAD

**Issue by rexxars** [sanity-io/gradient#447] opened 2017-09-22 09:35 UTC
Query: `* | order (_id asc) [10000...10100]`
Result: `500 Internal Server Error`
Elasticsearch says:
```
Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Result window is too large, from + size must be less than or equal to: [10000] but was [10100]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.
```

This might be obvious, but we need to address this somehow, and at least give a more meaningful error in the meantime.

**Comment by atombender** [comment] 2017-09-26 00:42
Offsets are generally problematic because a collection of documents may be modified while you're paginating, and they're inefficient because the entire collection up to the offset has to be sorted before the offset + limit window can be found. The solution is to implement stateful cursors (#18).

Let's make this issue about fixing the error message?

**Comment by erikgrinaker** [comment] 2017-12-18 12:15
This was fixed by masking the ElasticSearch error, but this is the wrong fix since the ES error may be caused by us (not the user) and since it will include the batch range that Gradient uses for the specific page (e.g. 10000-10100), not the range that the user requests (e.g. 1-1000000).

This whole issue may be moot once the `elasticsearch-scrolling` branch is merged, since we will no longer use ES pagination. Revisit this then.

**Closed** 2017-12-20 10:00 UTC
Labels: bug/minor, Elasticsearch
