### ISSUE TITLE
Flat, chained joins do not work 

### ISSUE THREAD

**Issue by simen** [sanity-io/gradient#410] opened 2017-07-04 09:34 UTC
This works:

`person->{"ass":image.asset->url}`

but this yields nothing:

`person->image.asset->url`

**Comment by atombender** [comment] 2017-07-04 22:06
Precedence? Try parantheses around the dotted expression.

**Comment by erikgrinaker** [comment] 2017-11-28 11:06
This seems to work for me, closing. Query:

```
*[_type == "screening" && _id == "screening_1_movie_10681"]{_id, title, "image":movie->poster.asset->url}
```

Result:
```
[{"_id":"screening_1_movie_10681","image":"https://cdn.sanity.io/images/zp7mbokg/production/yBfvxRUDocpLIFTkLVeIzF7U-1000x1500.jpg","title":"First ever screening of WALL·E!"}]
```

**Closed by erikgrinaker** 2017-11-28 11:06 UTC
Labels: bug/major

**Comment by erikgrinaker** [comment] 2017-11-28 14:21
(dupe of #415)
